apiVersion: v1
kind: Service
metadata:
  name: seelandcenter-service
  namespace: seelandcenter
spec:
  type: NodePort
  selector:
    app: seelandcenter
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
